In [40]:
import kagglehub
import pandas as pd
import os
# Download latest version
path = kagglehub.dataset_download("rhythmghai/food-ordering-behavior-india-50k-orders")
print(os.listdir(path))
df = pd.read_csv(os.path.join(path, os.listdir(path)[0]))
print(df)

['food_ordering_behavior_dataset.csv']
       order_id  user_id  age        city order_time day_type       cuisine  \
0             1     2698   35        Pune    Evening  Weekend       Chinese
1             2     3237   44      Mumbai      Night  Weekend  South Indian
2             3     3626   31       Delhi    Morning  Weekend       Biryani
3             4     3176   23       Delhi    Evening  Weekend       Biryani
4             5     4824   26  Chandigarh    Morning  Weekday       Chinese
...         ...      ...  ...         ...        ...      ...           ...
49995     49996     3569   40   Hyderabad  Afternoon  Weekday  North Indian
49996     49997     1087   42  Chandigarh    Morning  Weekend     Fast Food
49997     49998     3645   35        Pune    Morning  Weekday  South Indian
49998     49999     3630   34       Delhi    Morning  Weekend      Desserts
49999     50000     1258   20  Chandigarh    Morning  Weekday     Fast Food

       meal_type restaurant_type  order_value discount_applied  delivery_fee  \
0         Dinner         Premium          971              Yes            90
1         Dinner          Budget          442               No            26
2      Breakfast       Mid-range          739              Yes            85
3         Snacks       Mid-range          466               No            44
4          Lunch         Premium          927              Yes            58
...          ...             ...          ...              ...           ...
49995      Lunch         Premium          734              Yes            87
49996      Lunch       Mid-range          764              Yes            24
49997     Snacks          Budget          985              Yes            53
49998     Snacks         Premium          860              Yes            48
49999      Lunch       Mid-range          583               No            84

       time_taken_to_order  rating_given is_repeat_order         mood  \
0                       13             1             Yes  Celebrating
1                       13             2              No         Lazy
2                       10             2             Yes        Happy
3                       12             2              No        Happy
4                       13             2              No        Happy
...                    ...           ...             ...          ...
49995                    6             5              No        Happy
49996                   14             5              No        Happy
49997                    2             5             Yes         Lazy
49998                    6             3             Yes        Happy
49999                   13             3              No         Lazy

      hunger_level  company rainy_weather
0             High  Partner            No
1              Low   Family            No
2           Medium  Friends            No
3           Medium    Alone            No
4           Medium  Partner           Yes
...            ...      ...           ...
49995         High  Friends           Yes
49996          Low    Alone            No
49997       Medium    Alone           Yes
49998          Low    Alone           Yes
49999         High   Family            No

[50000 rows x 19 columns]

In [45]:
df.columns

Index(['order_id', 'user_id', 'age', 'city', 'order_time', 'day_type',
       'cuisine', 'meal_type', 'restaurant_type', 'order_value',
       'discount_applied', 'delivery_fee', 'time_taken_to_order',
       'rating_given', 'is_repeat_order', 'mood', 'hunger_level', 'company',
       'rainy_weather'],
      dtype='str')

remove unwanted columns

In [46]:
df.head()

,order_id,user_id,age,city,order_time,day_type,cuisine,meal_type,restaurant_type,order_value,discount_applied,delivery_fee,time_taken_to_order,rating_given,is_repeat_order,mood,hunger_level,company,rainy_weather
0,1,2698,35,Pune,Evening,Weekend,Chinese,Dinner,Premium,971,Yes,90,13,1,Yes,Celebrating,High,Partner,No
1,2,3237,44,Mumbai,Night,Weekend,South Indian,Dinner,Budget,442,No,26,13,2,No,Lazy,Low,Family,No
2,3,3626,31,Delhi,Morning,Weekend,Biryani,Breakfast,Mid-range,739,Yes,85,10,2,Yes,Happy,Medium,Friends,No
3,4,3176,23,Delhi,Evening,Weekend,Biryani,Snacks,Mid-range,466,No,44,12,2,No,Happy,Medium,Alone,No
4,5,4824,26,Chandigarh,Morning,Weekday,Chinese,Lunch,Premium,927,Yes,58,13,2,No,Happy,Medium,Partner,Yes

Questions:

1. Does hunger_level actually predict order_value? (do hungrier people spend more?)
2. Which city orders most, and do cities differ in cuisine preference?

## Do Hungrier People Spend More?

In [ ]:
hungyppl = df[["hunger_level","order_value"]]
hungyppl

      hunger_level  order_value
0             High          971
1              Low          442
2           Medium          739
3           Medium          466
4           Medium          927
...            ...          ...
49995         High          734
49996          Low          764
49997       Medium          985
49998          Low          860
49999         High          583

[50000 rows x 2 columns]

In [33]:
print(hungyppl["hunger_level"].value_counts())

hunger_level
High      16718
Low       16696
Medium    16586
Name: count, dtype: int64

In [34]:
print(hungyppl.groupby("hunger_level")["order_value"].mean()) #groupby, chooses all rows in hunger_level and pairs up w ordervalue

hunger_level
High      549.507118
Low       546.887698
Medium    546.789943
Name: order_value, dtype: float64

In [35]:
hungyppl.groupby("hunger_level")["order_value"].agg(["mean", "std", "min", "max"]) #agg allows to do more functions at once

                    mean         std  min  max
hunger_level
High          549.507118  259.719322  100  999
Low           546.887698  259.660095  100  999
Medium        546.789943  259.684841  100  999

Therefore hunger level does not affect how much is spent on food

## Which city orders most, and do cities differ in cuisine preference?

In [48]:
print(df[["city"]].value_counts())

city
Mumbai        8443
Pune          8354
Bangalore     8353
Delhi         8309
Chandigarh    8279
Hyderabad     8262
Name: count, dtype: int64